name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - run: cat /home/runner/.ssh/id_rsa
      - run: ls -la /home/runner/.ssh

      - run: git remote rename origin upstream
      - run: git remote add origin git@server.disconnect.cz:redirect.pehapkari.cz
      - run: git push origin main:production
